apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
  creationTimestamp: null
  generation: 1
  labels:
    run: raoa
  name: raoa
  selfLink: /apis/extensions/v1beta1/namespaces//deployments/raoa
spec:
  replicas: 1
  selector:
    matchLabels:
      run: raoa
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: raoa
    spec:
      containers:
      - image: registry.berg-turbenthal.ch:5000/raoa:latest
        imagePullPolicy: Always
        name: raoa
        resources: {}
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: "/data"
          name: data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: data
        persistentVolumeClaim: 
          claimName: photos-old-pvc
status: {}
