apiVersion: v1
kind: Namespace
metadata:
  name: raoa
spec:
  finalizers:
  - kubernetes
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
  creationTimestamp: null
  generation: 1
  labels:
    run: raoa
  name: raoa
  namespace: raoa
spec:
  replicas: 1
  selector:
    matchLabels:
      run: raoa
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: raoa
    spec:
      containers:
      - image: koa1/raoa:latest
        name: raoa
        resources: {}
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: "/data"
          name: data
        - mountPath: "/import"
          name: import
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: data
        persistentVolumeClaim: 
          claimName: photos-old-pvc
      - name: import
        hostPath: 
          path: /media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: 2017-05-12T07:41:50Z
  name: photos-old-pvc
  namespace: raoa
spec:
  resources:
    requests:
      storage: 2Ti
  accessModes:
    - ReadWriteOnce
